#!/usr/bin/env python3
"""Generate the Android-free builtin registry from the same JSON used by guest/website."""
from source_text import write_text as write_source_text, matches_text
import argparse
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
def generate():
    data=json.loads((ROOT/'app/src/main/assets/builtin-plugins.json').read_text(encoding='utf8'))
    if data.get('schema')!=1:raise ValueError('BUILTIN_REGISTRY_FORMAT')
    rows=data['plugins']; official=data['officialBundles']; seen=set()
    for row in rows+official:
        name=row['name']
        if not re.fullmatch(r'(?:@[a-z0-9._-]+/)?[a-z0-9._-]+',name) or name in seen or not isinstance(row['internal'],bool):raise ValueError('BUILTIN_REGISTRY_NAME')
        seen.add(name)
    for row in rows:
        if not re.fullmatch(r'/root/dsha-[a-z0-9-]+',row['guestDirectory']) or not re.fullmatch(r'(?:lib/)?index\.js',row['entrypoint']):raise ValueError('BUILTIN_REGISTRY_PATH')
    strings=lambda values:', '.join(json.dumps(value) for value in values)
    out='''package com.deepseekharness.app.util;
import java.util.List;
// Generated by tools/generate-builtin-plugins.py; edit assets/builtin-plugins.json.
public final class BuiltinPluginRegistry {
    private BuiltinPluginRegistry() { }
'''
    for key,values in [('DEFAULT', [x['name'] for x in rows if not x['internal']]),('SIGNED',[x['name'] for x in rows]),('OFFICIAL',[x['name'] for x in official]),('INTERNAL',[x['name'] for x in rows+official if x['internal']])]:
        out+=f'    public static final List<String> {key} = List.of({strings(values)});\n'
    for key,field in [('guestDirectory','guestDirectory'),('entrypoint','entrypoint')]:
        out+=f'    public static String {key}(String name) {{\n        if (name == null) return "";\n        return switch(name) {{\n'
        for row in rows:out+=f'            case {json.dumps(row["name"])} -> {json.dumps(row[field])};\n'
        out+='            default -> "";\n        };\n    }\n'
    return out+'}\n'
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--verify',action='store_true');args=parser.parse_args()
    path=ROOT/'app/src/main/java/com/deepseekharness/app/util/BuiltinPluginRegistry.java';content=generate()
    if args.verify:
        if not matches_text(path,content,encoding='utf8'):raise SystemExit('BUILTIN_REGISTRY_STALE')
    else:write_source_text(path,content,encoding='utf8')
if __name__=='__main__':main()
