#!/usr/bin/env python3
"""Generate the pure Java table from the shared, scope-specific filename rules."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'app/src/main/assets/credential-paths.json'
OUTPUT = ROOT / 'app/src/main/java/com/deepseekharness/app/util/CredentialPathRules.java'


def generate(raw):
    doc = json.loads(raw)
    if doc.get('schemaVersion') != 1:
        raise ValueError('CREDENTIAL_PATHS_SCHEMA')
    required = {'bridgeToken': '.bridge_token', 'bridgeHeaders': '.bridge_headers', 'bridgeStatus': '.bridge_status', 'legacyApiKey': '.dsha-apikey'}
    if doc.get('names') != required:
        raise ValueError('CREDENTIAL_PATHS_NAMES')
    arrays = {
        'MACHINE_EXACT': doc['externalMachine']['exact'],
        'MACHINE_PREFIXES': doc['externalMachine']['prefixes'],
        'BACKUP_ADDITIONAL': doc['backupMachine']['additionalExact'],
        'CREDENTIAL_EXACT': doc['externalCredentials']['exact'],
        'CREDENTIAL_PREFIXES': doc['externalCredentials']['prefixes'],
        'GUEST_PREFIXES': doc['externalDeniedGuestPrefixes'],
    }
    for name, values in arrays.items():
        if not isinstance(values, list) or len(values) != len(set(values)) or not values:
            raise ValueError('CREDENTIAL_PATHS_ARRAY:' + name)
        if any(not isinstance(v, str) or not v or '\\' in v or '\n' in v or '\r' in v or '\0' in v or v.startswith('/') for v in values):
            raise ValueError('CREDENTIAL_PATHS_VALUE:' + name)
    if not set(required.values()).difference({required['legacyApiKey']}) <= set(arrays['MACHINE_EXACT']) or '.anonymous-user-id' not in arrays['MACHINE_EXACT']:
        raise ValueError('CREDENTIAL_PATHS_REQUIRED_MACHINE')
    if doc['sessionExclusions'] != [{'root': 'sessions', 'relative': '.sessions-trash', 'recursive': True}]:
        raise ValueError('CREDENTIAL_PATHS_SESSION_SCOPE')
    lines = ['package com.deepseekharness.app.util;', '',
             '// Generated by tools/generate-credential-paths.py; source SHA-256: ' + hashlib.sha256(raw).hexdigest(),
             'final class CredentialPathRules {', '    private CredentialPathRules() { }']
    for name, value in required.items():
        field = {'bridgeToken': 'BRIDGE_TOKEN', 'bridgeHeaders': 'BRIDGE_HEADERS', 'bridgeStatus': 'BRIDGE_STATUS', 'legacyApiKey': 'LEGACY_API_KEY'}[name]
        lines.append('    static final String ' + field + '=' + json.dumps(value) + ';')
    for name, values in arrays.items():
        lines.append('    static final java.util.Set<String> ' + name + '=java.util.Set.of(' + ','.join(json.dumps(v) for v in values) + ');')
    lines += ['    static final String SESSION_ROOT="sessions", SESSION_TRASH=".sessions-trash";', '}', '']
    return '\n'.join(lines).encode('utf-8')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = generate(SOURCE.read_bytes())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != content:
            raise SystemExit('CREDENTIAL_PATHS_GENERATED_DRIFT')
        print('Credential paths JSON/Java scope table PASS')
    else:
        OUTPUT.write_bytes(content)


if __name__ == '__main__':
    main()
