package com.deepseekharness.app.util;

// Generated by tools/generate-credential-paths.py; source SHA-256: a11aee46add1e1cfde3700a3024a80bf6491a71e3a5744013ff4023a7baf5bae
final class CredentialPathRules {
    private CredentialPathRules() { }
    static final String BRIDGE_TOKEN=".bridge_token";
    static final String BRIDGE_HEADERS=".bridge_headers";
    static final String BRIDGE_STATUS=".bridge_status";
    static final String LEGACY_API_KEY=".dsha-apikey";
    static final java.util.Set<String> MACHINE_EXACT=java.util.Set.of(".bridge_token",".bridge_headers",".bridge_status",".anonymous-user-id","bridge-token",".dsha-bridge-token");
    static final java.util.Set<String> MACHINE_PREFIXES=java.util.Set.of(".bridge_token.",".bridge_headers.",".bridge_status.");
    static final java.util.Set<String> BACKUP_ADDITIONAL=java.util.Set.of(".plugins.lock",".dsha-web.pid",".dsha-web.identity",".dsha-stopped","dsha-startup-checkpoints",".offline-extracted",".offline-identity",".offline-version",".runtime-descriptor.json",".runtime-health.json","plugin-activations.json","plugin-safe-mode.json",".dsha-rc1-restore-generation");
    static final java.util.Set<String> CREDENTIAL_EXACT=java.util.Set.of(".env",".credentials",".dsha-apikey",".npmrc",".yarnrc.yml",".git-credentials");
    static final java.util.Set<String> CREDENTIAL_PREFIXES=java.util.Set.of(".env.",".credentials.");
    static final java.util.Set<String> GUEST_PREFIXES=java.util.Set.of("root/.dsha-");
    static final String SESSION_ROOT="sessions", SESSION_TRASH=".sessions-trash";
}
